# appspec.yml

version: 0.0
os: linux
files:
  - source: /
    destination: /home/ec2-user/postLike-logging/ # 프로젝트 이름
    overwrite: yes

permissions:
  - object: /
    pattern: "**"
    owner: ubuntu
    group: ubuntu